[#58] Use contentStyleFile instead of loadCSS in order to avoid security error In browser console there are the error at https://github.com/kumabook/stickynotes/issues/58:
SecurityError: The operation is insecure.